Repository bigbio/sdrf-pipelines, pull requests merged in 2024-10, with the labels that each got.

#179 Add setuptools dependency
  setup.py
Labels: dependencies, Review effort [1-5]: 1

#178 Fix ValueError on enzyme validation
  .github/workflows/ci.yml
  recipe/meta.yaml
  requirements-dev.txt
  requirements.txt
  sdrf_pipelines/sdrf/sdrf_schema.py
  setup.py
Labels: Bug fix, Review effort [1-5]: 2

#182 Fix column order validation
  sdrf_pipelines/sdrf/sdrf_schema.py
Labels: Bug fix, Review effort [1-5]: 2

#183 ignore case in original extension
  sdrf_pipelines/__init__.py
  sdrf_pipelines/openms/openms.py
  sdrf_pipelines/parse_sdrf.py
Labels: Review effort [1-5]: 2
